//
// Users.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


open class Users: Codable {

    public var id: Int32?
    public var name: String?
    public var avatar: String?
    public var isPremium: Bool?

    public init() {}

}
